<?php

namespace Database\Seeders;

use App\Models\Icon;
use Illuminate\Database\Seeder;

class IconSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $iconsData = [
            // ============================================================================
            // LUCIDE-REACT ICONS (Alphabetically sorted) - Currently used in project
            // ============================================================================
            ['key' => 'icon-alert-triangle', 'icon' => 'AlertTriangle', 'name' => 'Alert Triangle', 'library' => 'lucide-react'],
            ['key' => 'icon-arrow-left', 'icon' => 'ArrowLeft', 'name' => 'Arrow Left', 'library' => 'lucide-react'],
            ['key' => 'icon-arrow-right', 'icon' => 'ArrowRight', 'name' => 'Arrow Right', 'library' => 'lucide-react'],
            ['key' => 'icon-award', 'icon' => 'Award', 'name' => 'Award', 'library' => 'lucide-react'],
            ['key' => 'icon-bar-chart-3', 'icon' => 'BarChart3', 'name' => 'Bar Chart 3', 'library' => 'lucide-react'],
            ['key' => 'icon-book-open', 'icon' => 'BookOpen', 'name' => 'Book Open', 'library' => 'lucide-react'],
            ['key' => 'icon-briefcase', 'icon' => 'Briefcase', 'name' => 'Briefcase', 'library' => 'lucide-react'],
            ['key' => 'icon-calendar', 'icon' => 'Calendar', 'name' => 'Calendar', 'library' => 'lucide-react'],
            ['key' => 'icon-check-circle', 'icon' => 'CheckCircle', 'name' => 'Check Circle', 'library' => 'lucide-react'],
            ['key' => 'icon-chevron-down', 'icon' => 'ChevronDown', 'name' => 'Chevron Down', 'library' => 'lucide-react'],
            ['key' => 'icon-chevron-left', 'icon' => 'ChevronLeft', 'name' => 'Chevron Left', 'library' => 'lucide-react'],
            ['key' => 'icon-chevron-up', 'icon' => 'ChevronUp', 'name' => 'Chevron Up', 'library' => 'lucide-react'],
            ['key' => 'icon-clock', 'icon' => 'Clock', 'name' => 'Clock', 'library' => 'lucide-react'],
            ['key' => 'icon-code', 'icon' => 'Code', 'name' => 'Code', 'library' => 'lucide-react'],
            ['key' => 'icon-code2', 'icon' => 'Code2', 'name' => 'Code 2', 'library' => 'lucide-react'],
            ['key' => 'icon-coffee', 'icon' => 'Coffee', 'name' => 'Coffee', 'library' => 'lucide-react'],
            ['key' => 'icon-copy', 'icon' => 'Copy', 'name' => 'Copy', 'library' => 'lucide-react'],
            ['key' => 'icon-database', 'icon' => 'Database', 'name' => 'Database', 'library' => 'lucide-react'],
            ['key' => 'icon-download', 'icon' => 'Download', 'name' => 'Download', 'library' => 'lucide-react'],
            ['key' => 'icon-edit', 'icon' => 'Edit', 'name' => 'Edit', 'library' => 'lucide-react'],
            ['key' => 'icon-external-link', 'icon' => 'ExternalLink', 'name' => 'External Link', 'library' => 'lucide-react'],
            ['key' => 'icon-eye', 'icon' => 'Eye', 'name' => 'Eye', 'library' => 'lucide-react'],
            ['key' => 'icon-file-code', 'icon' => 'FileCode', 'name' => 'File Code', 'library' => 'lucide-react'],
            ['key' => 'icon-file-input', 'icon' => 'FileInput', 'name' => 'File Input', 'library' => 'lucide-react'],
            ['key' => 'icon-file-text', 'icon' => 'FileText', 'name' => 'File Text', 'library' => 'lucide-react'],
            ['key' => 'icon-file-x', 'icon' => 'FileX', 'name' => 'File X', 'library' => 'lucide-react'],
            ['key' => 'icon-folder', 'icon' => 'Folder', 'name' => 'Folder', 'library' => 'lucide-react'],
            ['key' => 'icon-folder-kanban', 'icon' => 'FolderKanban', 'name' => 'Folder Kanban', 'library' => 'lucide-react'],
            ['key' => 'icon-git-branch', 'icon' => 'GitBranch', 'name' => 'Git Branch', 'library' => 'lucide-react'],
            ['key' => 'icon-github', 'icon' => 'Github', 'name' => 'GitHub', 'library' => 'lucide-react'],
            ['key' => 'icon-globe', 'icon' => 'Globe', 'name' => 'Globe', 'library' => 'lucide-react'],
            ['key' => 'icon-heart', 'icon' => 'Heart', 'name' => 'Heart', 'library' => 'lucide-react'],
            ['key' => 'icon-help-circle', 'icon' => 'HelpCircle', 'name' => 'Help Circle', 'library' => 'lucide-react'],
            ['key' => 'icon-home', 'icon' => 'Home', 'name' => 'Home', 'library' => 'lucide-react'],
            ['key' => 'icon-layout-dashboard', 'icon' => 'LayoutDashboard', 'name' => 'Layout Dashboard', 'library' => 'lucide-react'],
            ['key' => 'icon-lightbulb', 'icon' => 'Lightbulb', 'name' => 'Lightbulb', 'library' => 'lucide-react'],
            ['key' => 'icon-link-2', 'icon' => 'Link2', 'name' => 'Link 2', 'library' => 'lucide-react'],
            ['key' => 'icon-linkedin', 'icon' => 'LinkedinIcon', 'name' => 'LinkedIn', 'library' => 'lucide-react'],
            ['key' => 'icon-loader-2', 'icon' => 'Loader2', 'name' => 'Loader 2', 'library' => 'lucide-react'],
            ['key' => 'icon-mail', 'icon' => 'Mail', 'name' => 'Mail', 'library' => 'lucide-react'],
            ['key' => 'icon-map-pin', 'icon' => 'MapPin', 'name' => 'Map Pin', 'library' => 'lucide-react'],
            ['key' => 'icon-menu', 'icon' => 'Menu', 'name' => 'Menu', 'library' => 'lucide-react'],
            ['key' => 'icon-message-circle', 'icon' => 'MessageCircle', 'name' => 'Message Circle', 'library' => 'lucide-react'],
            ['key' => 'icon-message-square', 'icon' => 'MessageSquare', 'name' => 'Message Square', 'library' => 'lucide-react'],
            ['key' => 'icon-package', 'icon' => 'Package', 'name' => 'Package', 'library' => 'lucide-react'],
            ['key' => 'icon-palette', 'icon' => 'Palette', 'name' => 'Palette', 'library' => 'lucide-react'],
            ['key' => 'icon-phone', 'icon' => 'Phone', 'name' => 'Phone', 'library' => 'lucide-react'],
            ['key' => 'icon-plus', 'icon' => 'Plus', 'name' => 'Plus', 'library' => 'lucide-react'],
            ['key' => 'icon-power', 'icon' => 'Power', 'name' => 'Power', 'library' => 'lucide-react'],
            ['key' => 'icon-refresh-cw', 'icon' => 'RefreshCw', 'name' => 'Refresh Counter Clockwise', 'library' => 'lucide-react'],
            ['key' => 'icon-rocket', 'icon' => 'Rocket', 'name' => 'Rocket', 'library' => 'lucide-react'],
            ['key' => 'icon-rotate-ccw', 'icon' => 'RotateCcw', 'name' => 'Rotate Counter Clockwise', 'library' => 'lucide-react'],
            ['key' => 'icon-save', 'icon' => 'Save', 'name' => 'Save', 'library' => 'lucide-react'],
            ['key' => 'icon-search', 'icon' => 'Search', 'name' => 'Search', 'library' => 'lucide-react'],
            ['key' => 'icon-send', 'icon' => 'Send', 'name' => 'Send', 'library' => 'lucide-react'],
            ['key' => 'icon-server', 'icon' => 'Server', 'name' => 'Server', 'library' => 'lucide-react'],
            ['key' => 'icon-settings', 'icon' => 'Settings', 'name' => 'Settings', 'library' => 'lucide-react'],
            ['key' => 'icon-share', 'icon' => 'Share2', 'name' => 'Share', 'library' => 'lucide-react'],
            ['key' => 'icon-shield', 'icon' => 'Shield', 'name' => 'Shield', 'library' => 'lucide-react'],
            ['key' => 'icon-shopping-cart', 'icon' => 'ShoppingCart', 'name' => 'Shopping Cart', 'library' => 'lucide-react'],
            ['key' => 'icon-smartphone', 'icon' => 'Smartphone', 'name' => 'Smartphone', 'library' => 'lucide-react'],
            ['key' => 'icon-snowflake', 'icon' => 'Snowflake', 'name' => 'Snowflake', 'library' => 'lucide-react'],
            ['key' => 'icon-sparkles', 'icon' => 'Sparkles', 'name' => 'Sparkles', 'library' => 'lucide-react'],
            ['key' => 'icon-star', 'icon' => 'Star', 'name' => 'Star', 'library' => 'lucide-react'],
            ['key' => 'icon-tag', 'icon' => 'Tag', 'name' => 'Tag', 'library' => 'lucide-react'],
            ['key' => 'icon-target', 'icon' => 'Target', 'name' => 'Target', 'library' => 'lucide-react'],
            ['key' => 'icon-terminal', 'icon' => 'Terminal', 'name' => 'Terminal', 'library' => 'lucide-react'],
            ['key' => 'icon-trash-2', 'icon' => 'Trash2', 'name' => 'Trash 2', 'library' => 'lucide-react'],
            ['key' => 'icon-undo-2', 'icon' => 'Undo2', 'name' => 'Undo 2', 'library' => 'lucide-react'],
            ['key' => 'icon-upload', 'icon' => 'Upload', 'name' => 'Upload', 'library' => 'lucide-react'],
            ['key' => 'icon-user', 'icon' => 'User', 'name' => 'User', 'library' => 'lucide-react'],
            ['key' => 'icon-users', 'icon' => 'Users', 'name' => 'Users', 'library' => 'lucide-react'],
            ['key' => 'icon-wrench', 'icon' => 'Wrench', 'name' => 'Wrench', 'library' => 'lucide-react'],
            ['key' => 'icon-x', 'icon' => 'X', 'name' => 'X', 'library' => 'lucide-react'],
            ['key' => 'icon-zap', 'icon' => 'Zap', 'name' => 'Zap', 'library' => 'lucide-react'],

            // ============================================================================
            // REACT-ICONS - FONT AWESOME 6 (Programming & Development)
            // ============================================================================
            ['key' => 'fa-code', 'icon' => 'FaCode', 'name' => 'Code', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-terminal', 'icon' => 'FaTerminal', 'name' => 'Terminal', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-laptop-code', 'icon' => 'FaLaptopCode', 'name' => 'Laptop Code', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-desktop', 'icon' => 'FaDesktop', 'name' => 'Desktop', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-laptop', 'icon' => 'FaLaptop', 'name' => 'Laptop', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-server', 'icon' => 'FaServer', 'name' => 'Server', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-database', 'icon' => 'FaDatabase', 'name' => 'Database', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-cloud', 'icon' => 'FaCloud', 'name' => 'Cloud', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-network-wired', 'icon' => 'FaNetworkWired', 'name' => 'Network Wired', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-bug', 'icon' => 'FaBug', 'name' => 'Bug', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-key', 'icon' => 'FaKey', 'name' => 'Key', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-lock', 'icon' => 'FaLock', 'name' => 'Lock', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-unlock', 'icon' => 'FaUnlock', 'name' => 'Unlock', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-shield-halved', 'icon' => 'FaShieldHalved', 'name' => 'Shield Halved', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-file-code', 'icon' => 'FaFileCode', 'name' => 'File Code', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-file-lines', 'icon' => 'FaFileLines', 'name' => 'File Lines', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-file', 'icon' => 'FaFile', 'name' => 'File', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-folder', 'icon' => 'FaFolder', 'name' => 'Folder', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-folder-open', 'icon' => 'FaFolderOpen', 'name' => 'Folder Open', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-gear', 'icon' => 'FaGear', 'name' => 'Gear', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-cog', 'icon' => 'FaCog', 'name' => 'Cog', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-screwdriver-wrench', 'icon' => 'FaScrewdriverWrench', 'name' => 'Screwdriver Wrench', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-wrench', 'icon' => 'FaWrench', 'name' => 'Wrench', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-toolbox', 'icon' => 'FaToolbox', 'name' => 'Toolbox', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-hammer', 'icon' => 'FaHammer', 'name' => 'Hammer', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-microchip', 'icon' => 'FaMicrochip', 'name' => 'Microchip', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-memory', 'icon' => 'FaMemory', 'name' => 'Memory', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-hard-drive', 'icon' => 'FaHardDrive', 'name' => 'Hard Drive', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-circle-nodes', 'icon' => 'FaCircleNodes', 'name' => 'Circle Nodes', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-diagram-project', 'icon' => 'FaDiagramProject', 'name' => 'Diagram Project', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-diagram-successor', 'icon' => 'FaDiagramSuccessor', 'name' => 'Diagram Successor', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-cube', 'icon' => 'FaCube', 'name' => 'Cube', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-cubes', 'icon' => 'FaCubes', 'name' => 'Cubes', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-puzzle-piece', 'icon' => 'FaPuzzlePiece', 'name' => 'Puzzle Piece', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-layer-group', 'icon' => 'FaLayerGroup', 'name' => 'Layer Group', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-object-group', 'icon' => 'FaObjectGroup', 'name' => 'Object Group', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-code-branch', 'icon' => 'FaCodeBranch', 'name' => 'Code Branch', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-code-merge', 'icon' => 'FaCodeMerge', 'name' => 'Code Merge', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-code-pull-request', 'icon' => 'FaCodePullRequest', 'name' => 'Code Pull Request', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-flask', 'icon' => 'FaFlask', 'name' => 'Flask', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-vial', 'icon' => 'FaVial', 'name' => 'Vial', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-vials', 'icon' => 'FaVials', 'name' => 'Vials', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-magnet', 'icon' => 'FaMagnet', 'name' => 'Magnet', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-atom', 'icon' => 'FaAtom', 'name' => 'Atom', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-diagram-next', 'icon' => 'FaDiagramNext', 'name' => 'Diagram Next', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-diagram-predecessor', 'icon' => 'FaDiagramPredecessor', 'name' => 'Diagram Predecessor', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-robot', 'icon' => 'FaRobot', 'name' => 'Robot', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-calculator', 'icon' => 'FaCalculator', 'name' => 'Calculator', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-chart-pie', 'icon' => 'FaChartPie', 'name' => 'Chart Pie', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-chart-area', 'icon' => 'FaChartArea', 'name' => 'Chart Area', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-chart-column', 'icon' => 'FaChartColumn', 'name' => 'Chart Column', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-lightbulb', 'icon' => 'FaLightbulb', 'name' => 'Lightbulb', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-flask-vial', 'icon' => 'FaFlaskVial', 'name' => 'Flask Vial', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-microscope', 'icon' => 'FaMicroscope', 'name' => 'Microscope', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-compress', 'icon' => 'FaCompress', 'name' => 'Compress', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-expand', 'icon' => 'FaExpand', 'name' => 'Expand', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-compress-arrows-alt', 'icon' => 'FaCompressArrowsAlt', 'name' => 'Compress Arrows Alt', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-arrows-alt', 'icon' => 'FaArrowsAlt', 'name' => 'Arrows Alt', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-sitemap', 'icon' => 'FaSitemap', 'name' => 'Sitemap', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-project-diagram', 'icon' => 'FaProjectDiagram', 'name' => 'Project Diagram', 'library' => 'react-icons/fa6'],
            
            // ============================================================================
            // REACT-ICONS - SIMPLE ICONS (Programming Languages & Technologies)
            // ============================================================================
            ['key' => 'si-javascript', 'icon' => 'SiJavascript', 'name' => 'JavaScript', 'library' => 'react-icons/si'],
            ['key' => 'si-typescript', 'icon' => 'SiTypescript', 'name' => 'TypeScript', 'library' => 'react-icons/si'],
            ['key' => 'si-python', 'icon' => 'SiPython', 'name' => 'Python', 'library' => 'react-icons/si'],
            ['key' => 'si-java', 'icon' => 'SiJava', 'name' => 'Java', 'library' => 'react-icons/si'],
            ['key' => 'si-php', 'icon' => 'SiPhp', 'name' => 'PHP', 'library' => 'react-icons/si'],
            ['key' => 'si-ruby', 'icon' => 'SiRuby', 'name' => 'Ruby', 'library' => 'react-icons/si'],
            ['key' => 'si-go', 'icon' => 'SiGo', 'name' => 'Go', 'library' => 'react-icons/si'],
            ['key' => 'si-rust', 'icon' => 'SiRust', 'name' => 'Rust', 'library' => 'react-icons/si'],
            ['key' => 'si-swift', 'icon' => 'SiSwift', 'name' => 'Swift', 'library' => 'react-icons/si'],
            ['key' => 'si-kotlin', 'icon' => 'SiKotlin', 'name' => 'Kotlin', 'library' => 'react-icons/si'],
            ['key' => 'si-cplusplus', 'icon' => 'SiCplusplus', 'name' => 'C++', 'library' => 'react-icons/si'],
            ['key' => 'si-csharp', 'icon' => 'SiCsharp', 'name' => 'C#', 'library' => 'react-icons/si'],
            ['key' => 'si-html5', 'icon' => 'SiHtml5', 'name' => 'HTML5', 'library' => 'react-icons/si'],
            ['key' => 'si-css3', 'icon' => 'SiCss3', 'name' => 'CSS3', 'library' => 'react-icons/si'],
            ['key' => 'si-react', 'icon' => 'SiReact', 'name' => 'React', 'library' => 'react-icons/si'],
            ['key' => 'si-vue', 'icon' => 'SiVue', 'name' => 'Vue.js', 'library' => 'react-icons/si'],
            ['key' => 'si-angular', 'icon' => 'SiAngular', 'name' => 'Angular', 'library' => 'react-icons/si'],
            ['key' => 'si-svelte', 'icon' => 'SiSvelte', 'name' => 'Svelte', 'library' => 'react-icons/si'],
            ['key' => 'si-nextdotjs', 'icon' => 'SiNextdotjs', 'name' => 'Next.js', 'library' => 'react-icons/si'],
            ['key' => 'si-nodedotjs', 'icon' => 'SiNodedotjs', 'name' => 'Node.js', 'library' => 'react-icons/si'],
            ['key' => 'si-laravel', 'icon' => 'SiLaravel', 'name' => 'Laravel', 'library' => 'react-icons/si'],
            ['key' => 'si-django', 'icon' => 'SiDjango', 'name' => 'Django', 'library' => 'react-icons/si'],
            ['key' => 'si-flask', 'icon' => 'SiFlask', 'name' => 'Flask', 'library' => 'react-icons/si'],
            ['key' => 'si-express', 'icon' => 'SiExpress', 'name' => 'Express', 'library' => 'react-icons/si'],
            ['key' => 'si-nestjs', 'icon' => 'SiNestjs', 'name' => 'NestJS', 'library' => 'react-icons/si'],
            ['key' => 'si-spring', 'icon' => 'SiSpring', 'name' => 'Spring', 'library' => 'react-icons/si'],
            ['key' => 'si-postgresql', 'icon' => 'SiPostgresql', 'name' => 'PostgreSQL', 'library' => 'react-icons/si'],
            ['key' => 'si-mysql', 'icon' => 'SiMysql', 'name' => 'MySQL', 'library' => 'react-icons/si'],
            ['key' => 'si-mongodb', 'icon' => 'SiMongodb', 'name' => 'MongoDB', 'library' => 'react-icons/si'],
            ['key' => 'si-redis', 'icon' => 'SiRedis', 'name' => 'Redis', 'library' => 'react-icons/si'],
            ['key' => 'si-sqlite', 'icon' => 'SiSqlite', 'name' => 'SQLite', 'library' => 'react-icons/si'],
            ['key' => 'si-amazonaws', 'icon' => 'SiAmazonaws', 'name' => 'AWS', 'library' => 'react-icons/si'],
            ['key' => 'si-googlecloud', 'icon' => 'SiGooglecloud', 'name' => 'Google Cloud', 'library' => 'react-icons/si'],
            ['key' => 'si-microsoftazure', 'icon' => 'SiMicrosoftazure', 'name' => 'Azure', 'library' => 'react-icons/si'],
            ['key' => 'si-docker', 'icon' => 'SiDocker', 'name' => 'Docker', 'library' => 'react-icons/si'],
            ['key' => 'si-kubernetes', 'icon' => 'SiKubernetes', 'name' => 'Kubernetes', 'library' => 'react-icons/si'],
            ['key' => 'si-git', 'icon' => 'SiGit', 'name' => 'Git', 'library' => 'react-icons/si'],
            ['key' => 'si-firebase', 'icon' => 'SiFirebase', 'name' => 'Firebase', 'library' => 'react-icons/si'],
            ['key' => 'si-vite', 'icon' => 'SiVite', 'name' => 'Vite', 'library' => 'react-icons/si'],
            ['key' => 'si-webpack', 'icon' => 'SiWebpack', 'name' => 'Webpack', 'library' => 'react-icons/si'],
            ['key' => 'si-tailwindcss', 'icon' => 'SiTailwindcss', 'name' => 'Tailwind CSS', 'library' => 'react-icons/si'],
            ['key' => 'si-bootstrap', 'icon' => 'SiBootstrap', 'name' => 'Bootstrap', 'library' => 'react-icons/si'],
            ['key' => 'si-materialdesign', 'icon' => 'SiMaterialdesign', 'name' => 'Material Design', 'library' => 'react-icons/si'],
            ['key' => 'si-figma', 'icon' => 'SiFigma', 'name' => 'Figma', 'library' => 'react-icons/si'],
            ['key' => 'si-adobexd', 'icon' => 'SiAdobexd', 'name' => 'Adobe XD', 'library' => 'react-icons/si'],
            ['key' => 'si-sketch', 'icon' => 'SiSketch', 'name' => 'Sketch', 'library' => 'react-icons/si'],

            // ============================================================================
            // REACT-ICONS - GENERAL PURPOSE ICONS (Font Awesome 6)
            // ============================================================================
            ['key' => 'fa-location-dot', 'icon' => 'FaLocationDot', 'name' => 'Location Dot', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-map-marker-alt', 'icon' => 'FaMapMarkerAlt', 'name' => 'Map Marker Alt', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-map', 'icon' => 'FaMap', 'name' => 'Map', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-address-book', 'icon' => 'FaAddressBook', 'name' => 'Address Book', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-address-card', 'icon' => 'FaAddressCard', 'name' => 'Address Card', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-building', 'icon' => 'FaBuilding', 'name' => 'Building', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-building-columns', 'icon' => 'FaBuildingColumns', 'name' => 'Building Columns', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-industry', 'icon' => 'FaIndustry', 'name' => 'Industry', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-factory', 'icon' => 'FaFactory', 'name' => 'Factory', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-warehouse', 'icon' => 'FaWarehouse', 'name' => 'Warehouse', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-school', 'icon' => 'FaSchool', 'name' => 'School', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-book', 'icon' => 'FaBook', 'name' => 'Book', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-book-open-reader', 'icon' => 'FaBookOpenReader', 'name' => 'Book Open Reader', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-briefcase', 'icon' => 'FaBriefcase', 'name' => 'Briefcase', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-handshake', 'icon' => 'FaHandshake', 'name' => 'Handshake', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-users', 'icon' => 'FaUsers', 'name' => 'Users', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-user-tie', 'icon' => 'FaUserTie', 'name' => 'User Tie', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-user-gear', 'icon' => 'FaUserGear', 'name' => 'User Gear', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-person-chalkboard', 'icon' => 'FaPersonChalkboard', 'name' => 'Person Chalkboard', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-chalkboard-user', 'icon' => 'FaChalkboardUser', 'name' => 'Chalkboard User', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-chart-line', 'icon' => 'FaChartLine', 'name' => 'Chart Line', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-chart-bar', 'icon' => 'FaChartBar', 'name' => 'Chart Bar', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-arrow-trend-up', 'icon' => 'FaArrowTrendUp', 'name' => 'Arrow Trend Up', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-arrow-trend-down', 'icon' => 'FaArrowTrendDown', 'name' => 'Arrow Trend Down', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-arrow-up-right-from-square', 'icon' => 'FaArrowUpRightFromSquare', 'name' => 'Arrow Up Right From Square', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-link', 'icon' => 'FaLink', 'name' => 'Link', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-paperclip', 'icon' => 'FaPaperclip', 'name' => 'Paperclip', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-image', 'icon' => 'FaImage', 'name' => 'Image', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-images', 'icon' => 'FaImages', 'name' => 'Images', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-video', 'icon' => 'FaVideo', 'name' => 'Video', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-film', 'icon' => 'FaFilm', 'name' => 'Film', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-music', 'icon' => 'FaMusic', 'name' => 'Music', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-palette', 'icon' => 'FaPalette', 'name' => 'Palette', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-paintbrush', 'icon' => 'FaPaintbrush', 'name' => 'Paintbrush', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-brush', 'icon' => 'FaBrush', 'name' => 'Brush', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-circle', 'icon' => 'FaCircle', 'name' => 'Circle', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-square', 'icon' => 'FaSquare', 'name' => 'Square', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-play', 'icon' => 'FaPlay', 'name' => 'Play', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-pause', 'icon' => 'FaPause', 'name' => 'Pause', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-stop', 'icon' => 'FaStop', 'name' => 'Stop', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-forward', 'icon' => 'FaForward', 'name' => 'Forward', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-backward', 'icon' => 'FaBackward', 'name' => 'Backward', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-calendar', 'icon' => 'FaCalendar', 'name' => 'Calendar', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-calendar-days', 'icon' => 'FaCalendarDays', 'name' => 'Calendar Days', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-clock', 'icon' => 'FaClock', 'name' => 'Clock', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-stopwatch', 'icon' => 'FaStopwatch', 'name' => 'Stopwatch', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-hourglass', 'icon' => 'FaHourglass', 'name' => 'Hourglass', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-bell', 'icon' => 'FaBell', 'name' => 'Bell', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-bell-slash', 'icon' => 'FaBellSlash', 'name' => 'Bell Slash', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-flag', 'icon' => 'FaFlag', 'name' => 'Flag', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-tag', 'icon' => 'FaTag', 'name' => 'Tag', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-tags', 'icon' => 'FaTags', 'name' => 'Tags', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-star', 'icon' => 'FaStar', 'name' => 'Star', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-heart', 'icon' => 'FaHeart', 'name' => 'Heart', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-thumbs-up', 'icon' => 'FaThumbsUp', 'name' => 'Thumbs Up', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-thumbs-down', 'icon' => 'FaThumbsDown', 'name' => 'Thumbs Down', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-share', 'icon' => 'FaShare', 'name' => 'Share', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-share-nodes', 'icon' => 'FaShareNodes', 'name' => 'Share Nodes', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-comment', 'icon' => 'FaComment', 'name' => 'Comment', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-comments', 'icon' => 'FaComments', 'name' => 'Comments', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-message', 'icon' => 'FaMessage', 'name' => 'Message', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-paper-plane', 'icon' => 'FaPaperPlane', 'name' => 'Paper Plane', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-inbox', 'icon' => 'FaInbox', 'name' => 'Inbox', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-print', 'icon' => 'FaPrint', 'name' => 'Print', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-qrcode', 'icon' => 'FaQrcode', 'name' => 'QR Code', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-barcode', 'icon' => 'FaBarcode', 'name' => 'Barcode', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-receipt', 'icon' => 'FaReceipt', 'name' => 'Receipt', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-cart-shopping', 'icon' => 'FaCartShopping', 'name' => 'Cart Shopping', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-credit-card', 'icon' => 'FaCreditCard', 'name' => 'Credit Card', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-wallet', 'icon' => 'FaWallet', 'name' => 'Wallet', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-money-bill', 'icon' => 'FaMoneyBill', 'name' => 'Money Bill', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-coins', 'icon' => 'FaCoins', 'name' => 'Coins', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-gift', 'icon' => 'FaGift', 'name' => 'Gift', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-trophy', 'icon' => 'FaTrophy', 'name' => 'Trophy', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-medal', 'icon' => 'FaMedal', 'name' => 'Medal', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-award', 'icon' => 'FaAward', 'name' => 'Award', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-certificate', 'icon' => 'FaCertificate', 'name' => 'Certificate', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-id-card', 'icon' => 'FaIdCard', 'name' => 'ID Card', 'library' => 'react-icons/fa6'],
            ['key' => 'fa-id-badge', 'icon' => 'FaIdBadge', 'name' => 'ID Badge', 'library' => 'react-icons/fa6'],
        ];

        // Remove duplicates by key (keep first occurrence)
        $uniqueIcons = [];
        $seenKeys = [];
        foreach ($iconsData as $icon) {
            if (!in_array($icon['key'], $seenKeys)) {
                $uniqueIcons[] = $icon;
                $seenKeys[] = $icon['key'];
            }
        }

        // Delete all existing icons
        Icon::query()->delete();

        // Insert icons
        foreach ($uniqueIcons as $iconData) {
            Icon::create($iconData);
        }

        $this->command->info('Icons seeded successfully! Total: ' . count($uniqueIcons));
    }
}
